### ISSUE TITLE
What is this traceback that I can't even trace back?

### ISSUE THREAD

**Issue by duruburak** [TomSchimansky/CustomTkinter#1006]
I'm fetching videos' data (such as thumbnails, authors, titles, viewcounts etc) in a playlist and place them in a toplevel, even tho it works it still throws hundreds of lines of errors. There are so many errors that I can't even scroll up to the very beginning. What causes this, any ideas?
Here's just a part of the traceback:
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 191, in _update_dimensions_event       
    self._draw(no_color_updates=True)  # faster drawing without color changes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_label.py", line 150, in _draw
    requires_recoloring = self._draw_engine.draw_rounded_rect_with_border(self._apply_widget_scaling(self._current_width),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_rendering\draw_engine.py", line 128, in draw_rounded_rect_with_border
    return self.__draw_rounded_rect_with_border_font_shapes(width, height, corner_radius, border_width, inner_corner_radius, ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_rendering\draw_engine.py", line 248, in __draw_rounded_rect_with_border_font_shapes
    self._canvas.delete("border_parts")
  File "D:\Python311\Lib\tkinter\__init__.py", line 2879, in delete
    self.tk.call((self._w, 'delete') + args)
_tkinter.TclError: invalid command name ".!ctktoplevel.!ctklabel111.!ctkcanvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 191, in _update_dimensions_event       
    self._draw(no_color_updates=True)  # faster drawing without color changes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_label.py", line 150, in _draw
    requires_recoloring = self._draw_engine.draw_rounded_rect_with_border(self._apply_widget_scaling(self._current_width),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_rendering\draw_engine.py", line 128, in draw_rounded_rect_with_border
    return self.__draw_rounded_rect_with_border_font_shapes(width, height, corner_radius, border_width, inner_corner_radius, ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_rendering\draw_engine.py", line 248, in __draw_rounded_rect_with_border_font_shapes
    self._canvas.delete("border_parts")
  File "D:\Python311\Lib\tkinter\__init__.py", line 2879, in delete
    self.tk.call((self._w, 'delete') + args)
_tkinter.TclError: invalid command name ".!ctktoplevel.!ctklabel112.!ctkcanvas"
```

**Comment by TomSchimansky** [comment]
Can you post your code? Or a small example that produces these errors?

**Comment by duruburak** [comment]
> Can you post your code? Or a small example that produces these errors?

This is the simplest form I can make:
(Images in the attachments)
```python
def splash_screen():

    splash_screen = customtkinter.CTkToplevel(screen)

    global is_top_level_ready
    is_top_level_ready = False

    frame = customtkinter.CTkFrame(splash_screen, width=427, height=250, fg_color="gray14", bg_color="gray14")
    frame.place(x=0, y=0)

    label1 = customtkinter.CTkLabel(splash_screen, text='Please wait...', fg_color="gray14", bg_color="gray14", font=("Game Of Squids", 21, "bold"))
    label1.place(x=122, y=120)

    image_a = customtkinter.CTkImage(dark_image=Image.open('dot_light.png'))
    image_b = customtkinter.CTkImage(dark_image=Image.open('dot_dark.png'))

    while True:

        if is_top_level_ready == False:
            l1 = customtkinter.CTkLabel(master=splash_screen, image=image_a, fg_color="gray14", bg_color="gray14", text="").place(x=180, y=165)
            l2 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=215, y=165)
            l3 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=250, y=165)
            l4 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=285, y=165)
            splash_screen.update_idletasks()
            time.sleep(0.2)

            l1 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=180, y=165)
            l2 = customtkinter.CTkLabel(master=splash_screen, image=image_a, fg_color="gray14", bg_color="gray14", text="").place(x=215, y=165)
            l3 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=250, y=165)
            l4 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=285, y=165)
            splash_screen.update_idletasks()
            time.sleep(0.2)

            l1 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=180, y=165)
            l2 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=215, y=165)
            l3 = customtkinter.CTkLabel(master=splash_screen, image=image_a, fg_color="gray14", bg_color="gray14", text="").place(x=250, y=165)
            l4 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=285, y=165)
            splash_screen.update_idletasks()
            time.sleep(0.2)

            l1 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=180, y=165)
            l2 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=215, y=165)
            l3 = customtkinter.CTkLabel(master=splash_screen, image=image_b, fg_color="gray14", bg_color="gray14", text="").place(x=250, y=165)
            l4 = customtkinter.CTkLabel(master=splash_screen, image=image_a, fg_color="gray14", bg_color="gray14", text="").place(x=285, y=165)
            splash_screen.update_idletasks()
            time.sleep(0.2)

        else:
            splash_screen.destroy()
            break

    the_toplevel = customtkinter.CTkToplevel(screen, fg_color="gray14")
    the_toplevel.minsize(width=650, height=415)
    the_toplevel.grid_rowconfigure(0, weight=0)
    the_toplevel.grid_columnconfigure(0, weight=0)
    
def break_loop():
    global is_top_level_ready
    is_top_level_ready = True    
```
```python
screen = customtkinter.CTk()

button = customtkinter.CTkButton(screen, command=break_loop)
button.pack(pady=30, padx=30)

threading.Thread(target=splash_screen).start()

screen.mainloop()
```
![dot_dark](https://user-images.githubusercontent.com/100048974/211125058-75affce8-0abd-45ad-8132-945569d48128.png)
![dot_light](https://user-images.githubusercontent.com/100048974/211125059-5c64a9af-6070-4c9b-9936-59a956d2a148.png)

**Comment by DomGravante** [comment]
For what it's worth, here is a simpler form that gets to the heart of the issue. Warning that running this example may cause program to continue running in background, so kill the process after the error is raised.

Similar error message. Error occurs when running in a thread, but not when out of the thread. 
If you replace the ctk widgets with tkinter widgets, error does not occur. 

```py
import time, threading
import tkinter, customtkinter

app = customtkinter.CTk()
app.geometry("400x400")

def delete_app():
    # Produces Error
    t1 = threading.Thread(target=d).start()
    
    # Produces no error
    # d()

def d():
    time.sleep(1)
    app.destroy()
    

frame_1 = customtkinter.CTkFrame(master=app)
frame_1.pack(pady=20, padx=60, fill="both", expand=True)

label_1 = customtkinter.CTkLabel(master=frame_1, justify=tkinter.LEFT, text="Unimportant Text Label")
label_1.pack(pady=10, padx=10)

button_1 = customtkinter.CTkButton(master=frame_1, command=delete_app, text="Destroy App Window")
button_1.pack(pady=10, padx=10)

app.mainloop()
```

**Comment by TomSchimansky** [comment]
Tkinter and CustomTkinter are not thread save and CustomTkinter actions cannot be started from other threads than the main thread. So you have to create a loop in the main thread and check for messages from the other thread. This could be implemented like this:
```
import time, threading
import tkinter, customtkinter

app = customtkinter.CTk()
app.geometry("400x400")

thread_signal = False

def delete_app():
    t1 = threading.Thread(target=d).start()

def d():
    global thread_signal
    time.sleep(1)
    thread_signal = True

def control_loop():
    global thread_signal
    if thread_signal:
        app.destroy()
    else:
        app.after(100, control_loop)


frame_1 = customtkinter.CTkFrame(master=app)
frame_1.pack(pady=20, padx=60, fill="both", expand=True)

label_1 = customtkinter.CTkLabel(master=frame_1, justify=tkinter.LEFT, text="Unimportant Text Label")
label_1.pack(pady=10, padx=10)

button_1 = customtkinter.CTkButton(master=frame_1, command=delete_app, text="Destroy App Window")
button_1.pack(pady=10, padx=10)

app.after(100, control_loop)  # start control loop in main thread
app.mainloop()
```
But you should use a class structure to avoid global variables.

**Comment by duruburak** [comment]
> Tkinter and CustomTkinter are not thread save and CustomTkinter actions cannot be started from other threads than the main thread. So you have to create a loop in the main thread and check for messages from the other thread. This could be implemented like this:
> 
> ```python
> import time, threading
> import tkinter, customtkinter
> 
> app = customtkinter.CTk()
> app.geometry("400x400")
> 
> thread_signal = False
> 
> def delete_app():
>     t1 = threading.Thread(target=d).start()
> 
> def d():
>     global thread_signal
>     time.sleep(1)
>     thread_signal = True
> 
> def control_loop():
>     global thread_signal
>     if thread_signal:
>         app.destroy()
>     else:
>         app.after(100, control_loop)
> 
> 
> frame_1 = customtkinter.CTkFrame(master=app)
> frame_1.pack(pady=20, padx=60, fill="both", expand=True)
> 
> label_1 = customtkinter.CTkLabel(master=frame_1, justify=tkinter.LEFT, text="Unimportant Text Label")
> label_1.pack(pady=10, padx=10)
> 
> button_1 = customtkinter.CTkButton(master=frame_1, command=delete_app, text="Destroy App Window")
> button_1.pack(pady=10, padx=10)
> 
> app.after(100, control_loop)  # start control loop in main thread
> app.mainloop()
> ```
> 
> But you should use a class structure to avoid global variables.

Thank you so much, this helped a lot. Also can I ask why did you use `Thread` for delete_app() and `sleep` in d()?
