### ISSUE TITLE
Can't even run the Customtkinter itself

### ISSUE THREAD

**Issue by ajayschoo** [TomSchimansky/CustomTkinter#101]
I imported the customtkinert with simple code of main window but it didn't run putting an error:

Traceback (most recent call last):
  File "C:/Users/ajay.bhati/PycharmProjects/Python Project/Sam.py", line 2, in <module>
    import customtkinter
  File "C:\Users\ajay.bhati\PycharmProjects\Python Project\venv\lib\site-packages\customtkinter\__init__.py", line 40, in <module>
    from .widgets.ctk_button import CTkButton
  File "C:\Users\ajay.bhati\PycharmProjects\Python Project\venv\lib\site-packages\customtkinter\widgets\ctk_button.py", line 9, in <module>
    from .widget_base_class import CTkBaseClass
  File "C:\Users\ajay.bhati\PycharmProjects\Python Project\venv\lib\site-packages\customtkinter\widgets\widget_base_class.py", line 5, in <module>
    from typing import Callable, Union, TypedDict
ImportError: cannot import name 'TypedDict' from 'typing' (C:\Program Files (x86)\Python37-32\lib\typing.py)

**Comment by felipetesc** [comment]
Can You post your code with the correct indentation ?

**Comment by demberto** [comment]
Ofcourse it will fail, `TypedDict` was introduced in Python 3.8, although it can still be imported from `typing_extensions` in Python 3.7, On my way to file a PR for this 🚀
