### ISSUE TITLE
When i am converting in exe it shows error 

### ISSUE THREAD

**Issue by surajkumar2499** [TomSchimansky/CustomTkinter#124]
Traceback (most recent call last):
  File "img.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\__init__.py", line 16, in <module>
  File "customtkinter\theme_manager.py", line 16, in load_theme
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hp\\AppData\\Local\\Temp\\_MEI248682\\customtkinter\\assets\\themes\\blue.json'

**Comment by ZelKed** [comment]
copy the customtkinter folder add add it to dist or build and run it

**Comment by surajkumar2499** [comment]
THANKYOU

**Comment by ZelKed** [comment]
No problem, i had the same problem

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging
