### ISSUE TITLE
No attribute CTkScrollableFrame

### ISSUE THREAD

**Issue by inyoka** [TomSchimansky/CustomTkinter#1285]
The following error occurs when running any of the example code files with a ScrollableFrame : 

AttributeError: module 'customtkinter' has no attribute 'CTkScrollableFrame'

```
Traceback (most recent call last):
  File "/CustomTkinter/examples/scrollable_frame_example.py", line 6, in <module>
    class ScrollableCheckBoxFrame(customtkinter.CTkScrollableFrame):
AttributeError: module 'customtkinter' has no attribute 'CTkScrollableFrame'
```

```
  File "/CustomTkinter/examples/complex_example.py", line 163, in <module>
    app = App()
  File "/CustomTkinter/examples/complex_example.py", line 109, in __init__
    self.scrollable_frame = customtkinter.CTkScrollableFrame(self, label_text="CTkScrollableFrame")
AttributeError: module 'customtkinter' has no attribute 'CTkScrollableFrame'
```
Let me know if I can provide any more details.
Regards, Inyoka

**Comment by ElectricCandlelight** [comment]
Possible duplicate of #1232 and #1253 

Please try upgrading to the latest version

pip3 install customtkinter --upgrade

**Comment by inyoka** [comment]
Hi, thank you.  Yes sorry it works correctly from pip.  I was pulling directly from the master branch so I could run the examples.
CTk is awesome btw, so thank you.
