### ISSUE TITLE
`set_default_color_theme` went wrong

### ISSUE THREAD

**Issue by xicrosoft** [TomSchimansky/CustomTkinter#1408]
macOS Ventura
Python 3.11.1

```Traceback (most recent call last):
  File "/path/main.py", line 7, in <module>
    customtkinter.set_default_color_theme("custom_theme.json")
  File "/path/venv/lib/python3.11/site-packages/customtkinter/__init__.py", line 67, in set_default_color_theme
    ThemeManager.load_theme(color_string)
  File "/path/venv/lib/python3.11/site-packages/customtkinter/windows/widgets/theme/theme_manager.py", line 30, in load_theme
    if "macOS" in cls.theme[key].keys():
                  ^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'keys'
```

**Comment by xicrosoft** [comment]
> macOS Ventura Python 3.11.1
> 
> ```
>   File "/path/main.py", line 7, in <module>
>     customtkinter.set_default_color_theme("custom_theme.json")
>   File "/path/venv/lib/python3.11/site-packages/customtkinter/__init__.py", line 67, in set_default_color_theme
>     ThemeManager.load_theme(color_string)
>   File "/path/venv/lib/python3.11/site-packages/customtkinter/windows/widgets/theme/theme_manager.py", line 30, in load_theme
>     if "macOS" in cls.theme[key].keys():
>                   ^^^^^^^^^^^^^^^^^^^
> AttributeError: 'int' object has no attribute 'keys'
> ```

**Comment by xicrosoft** [comment]
It's my problem, I mistyped the json file address
