### ISSUE TITLE
CTkLabel regression

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#1466]
Hi. I am migrating from CustomTkinter 4 to 5.1.2 and now encountering an exception:
```

        self.widget = ctk.CTkLabel(master,
                                   relief=tk.SUNKEN,
                                   text='',
                                   anchor='w')
```
The relief=tk.SUNKEN was accepted with V4.

This raises the exception:

```
Traceback (most recent call last):
  File "/home/clive/PycharmProjects/ctk5_theme_builder/ctk_theme_builder.py", line 2819, in <module>
    controller = ControlPanel()
  File "/home/clive/PycharmProjects/ctk5_theme_builder/ctk_theme_builder.py", line 312, in __init__
    self._status_bar = cbtk.CBtkStatusBar(master=self.ctk_control_panel,
  File "/home/clive/PycharmProjects/ctk5_theme_builder/lib/cbtk_kit.py", line 492, in __init__
    self.widget = ctk.CTkLabel(master, relief=tk.SUNKEN,
  File "/home/clive/PycharmProjects/ctk5_theme_builder/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/ctk_label.py", line 90, in __init__
    check_kwargs_empty(kwargs, raise_error=True)
  File "/home/clive/PycharmProjects/ctk5_theme_builder/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/utility/utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['relief'] are not supported arguments. Look at the documentation for supported arguments.
```

**Comment by bfedie518** [comment]
I just added this in a pull request #1467

**Comment by avalon60** [comment]
Thanks.

**Comment by TomSchimansky** [comment]
I don't think the tkinter relief fits the style of CustomTkinter, if you want a a relief or tkinter border you can just use a tkinter .Label.
