### ISSUE TITLE
Installer fails to launch due to .json theme file unavailablity : FileNotFoundError

### ISSUE THREAD

**Issue by GiuliaGualtieri** [TomSchimansky/CustomTkinter#1498]
Hi Tom, 

I'm trying to use pyinstaller in order to create the application of one of my project and I got this `FileNotFoundError`:

```
C:\Users\Administrator\Desktop>wingman_flex.exe
Traceback (most recent call last):
  File "customtkinter\windows\widgets\theme\__init__.py", line 5, in <module>
  File "customtkinter\windows\widgets\theme\theme_manager.py", line 18, in load_theme
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\path\\to\\packages\\customtkinter\\windows\\widgets\\theme\\../../../assets\\themes\\blue.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wingman_flex.py", line 2, in <module>
    import customtkinter as ctk
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "customtkinter\__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "customtkinter\windows\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "customtkinter\windows\ctk_tk.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "customtkinter\windows\widgets\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "customtkinter\windows\widgets\ctk_button.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "customtkinter\windows\widgets\theme\__init__.py", line 7, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\path\\to\\packages\\customtkinter\\windows\\widgets\\theme\\../../../assets\\themes\\blue.json'
```

The .json theme file for CustomTkinter could not be found.

This error was already mentioned in  #1170 . 

Anyway I would like to suggest a modification. 
Instead of:
https://github.com/TomSchimansky/CustomTkinter/blob/2ee496ed28ece351ce53b63ca5eed90267735c44/customtkinter/windows/widgets/theme/theme_manager.py#L18
I suggest to write:
```python
with open(os.path.join(script_directory, os.path("../../../assets"), "themes", f"{theme_name_or_path}.json"), "r") as f:
```
on this way your code is OS free, does not depend on a specific OS.

Thanks in advance for the time and attention. Good work!
Giulia

**Comment by TomSchimansky** [comment]
Thanks for the tip with the parent directory, I will change this. 
And regarding you error when packaging, this is a know problem also mentioned in the docs: https://customtkinter.tomschimansky.com/documentation/packaging
PyInstaller fails to package non .py files for some reason, but the library folder can be added manually.
