### ISSUE TITLE
KeyError: 'text' when trying to set custom color theme

### ISSUE THREAD

**Issue by f1refa11** [TomSchimansky/CustomTkinter#1515]
code:
```python
import customtkinter

customtkinter.set_default_color_theme("aaa.json")
app = customtkinter.CTk()
app.title("test")
app.geometry("600x350")

app.mainloop()
```
error:
```
Traceback (most recent call last):
  File "c:\Users\user\Documents\[app path]\main.py", line 3, in <module>
    customtkinter.set_default_color_theme("aaa.json")
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\customtkinter\__init__.py", line 89, in set_default_color_theme
    ThemeManager.load_theme(color_string)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\customtkinter\theme_manager.py", line 25, in load_theme
    cls.theme["text"] = cls.theme["text"]["Windows"]
KeyError: 'text'
```

**Comment by f1refa11** [comment]
Resolved issue by updating the library😅
