### ISSUE TITLE
CTkToolTip works on pretty much all widgets except CTkTabview - exception raised.

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#1532]
I have started using CTkToolTip (by https://github.com/Akascape) on most widget types. This works great except for the CTkTabview widget.

Modifying the complex_example.py reproduces this error:

        # create tabview
        self.tabview = customtkinter.CTkTabview(self, width=250)
        self.tabview.grid(row=0, column=2, padx=(20, 0), pady=(20, 0), sticky="nsew")
        self.tabview.add("CTkTabview")
        self.tabview.add("Tab 2")
        self.tabview.add("Tab 3")
        self.tabview.tab("CTkTabview").grid_columnconfigure(0, weight=1)  # configure grid of individual tabs
        self.tabview.tab("Tab 2").grid_columnconfigure(0, weight=1)

        tooltip = CTkToolTip(self.tabview,
                             justify="left",
                             wraplength=250,
                             padding=(5, 5),
                             message='This tooltip will fail for CTkTabview widgets')

The exception raised is:

```
Traceback (most recent call last):
  File "/home/clive/PycharmProjects/ctk5_theme_builder/complex_example.py", line 180, in <module>
    app = App()
  File "/home/clive/PycharmProjects/ctk5_theme_builder/complex_example.py", line 70, in __init__
    tooltip = CTkToolTip(self.tabview,
  File "/home/clive/PycharmProjects/ctk5_theme_builder/lib/ctk_tooltip/ctk_tooltip.py", line 92, in __init__
    self.widget.bind("<Enter>", self.on_enter, add="+")
  File "/home/clive/PycharmProjects/ctk5_theme_builder/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py", line 244, in bind
    raise NotImplementedError
NotImplementedError
```
I realise that CTkTooltip is not part of CustomTkinter, but this looks like it might be an issue with CustomTkinter.

**Comment by MaxNiark** [comment]
Hey avalon60,

Could you help me with my rendering issue ? 

thanks,

**Comment by pospimi** [comment]
Hi, 

I have just encountered a similar issue with the CTkTabview.

This code raises error "NotImplementedError" after calling the "bind" method.

`from customtkinter import *

window = CTk()

def tabChanged(event):
    print("tab changed")

tabView = CTkTabview(master=window)
tabView.pack(fill="both", expand=True)
tabList = ["tab1", "tab2"]
for tab in tabList:
    tabView.add(tab)
tabView.set(tabList[0])
# the issue is here (NotImplementedError error)
tabView.bind("<<NotebookTabChanged>>", tabChanged)

window.mainloop()`

Michal

**Comment by pospimi** [comment]
> Hi,
> 
> I have just encountered a similar issue with the CTkTabview.
> 
> This code raises error "NotImplementedError" after calling the "bind" method.
> 
> from customtkinter import *
> 
> window = CTk()
> 
> def tabChanged(event): print("tab changed")
> 
> tabView = CTkTabview(master=window) tabView.pack(fill="both", expand=True) tabList = ["tab1", "tab2"] for tab in tabList: tabView.add(tab) tabView.set(tabList[0])
> 
> tabView.bind("<>", tabChanged)
> 
> window.mainloop()
> 
> Michal

FIXED by using the original Tkinter notebook object instead of the TabView:

notebookWidget = tabView.nametowidget(tabView.winfo_children()[0])
notebookWidget.bind("<<NotebookTabChanged>>", tabChanged)

**Comment by Akascape** [comment]
@avalon60 Have you tried passing `self.tabview.tab("Tab_name")`  instead of `self.tabview` as the master widget?
```
 tooltip = CTkToolTip(self.tabview.tab("Tab 2"),
                         justify="left",
                         wraplength=250,
                         padding=(5, 5),
                         message='This tooltip will fail for CTkTabview widgets')
...
```

**Comment by avalon60** [comment]
> @avalon60 Have you tried passing `self.tabview.tab("Tab_name")` instead of `self.tabview` as the master widget?
> 
> ```
>  tooltip = CTkToolTip(self.tabview.tab("Tab 2"),
>                          justify="left",
>                          wraplength=250,
>                          padding=(5, 5),
>                          message='This tooltip will fail for CTkTabview widgets')
> ...
> ```

Yes that works, but of course you then need to create a tooltip for every tab added.

**Comment by avalon60** [comment]
I just reproduced this with another tooltip class and got the same result. Pretty sure this is CustomTkinter.
