### ISSUE TITLE
Cannot run a PyInstaller packaged application from command line or subprocess.Popen.

### ISSUE THREAD

**Issue by gamartin23** [TomSchimansky/CustomTkinter#1556]
As i developed more and more tools for my team using CTK (great work, btw), i got instructed to build a "launcher" for the tools, so i thought about launching them with any of the subprocess or any kind of method that calls the .exe from the command line.
In every single method, this error was found:

Failed to execute script 'rewrite' due to unhandled exception: bitmap "appicon.ico" not defined.
Traceback (most recent call last):
  File "rewrite.py", line 65, in <module>
  File "customtkinter\windows\ctk_tk.py", line 226, in wm_iconbitmap
    super().wm_iconbitmap(bitmap, default)
  File "tkinter\__init__.py", line 2136, in wm_iconbitmap
_tkinter.TclError: bitmap "appicon.ico" not defined

the "rewrite" executable has an icon assigned, as well as defined in the pre-packaged script.
Running cmd and calling the program from there works fine, but doing so from another app or python script results in this error message, constantly.
![imagen_2023-05-02_023935239](https://user-images.githubusercontent.com/105208079/235587697-8504d03f-9791-4795-896f-fa3c2e7c8cac.png)

**Comment by gamartin23** [comment]
darn i feel stupid.
subprocess.run(['path/to/rewrite.exe'], cwd='path/to/')
did work just fine.
