### ISSUE TITLE
CTkComboBox opens a tab when clicked

### ISSUE THREAD

**Issue by Naatan** [TomSchimansky/CustomTkinter#156]
Use:

```
import tkinter
from customtkinter import *

app = CTk()
CTkComboBox(app, values=["test"]).pack(padx=10, side=tkinter.TOP)
app.mainloop()
```

When you click the combo box a new tab will open. eg.

https://user-images.githubusercontent.com/278649/172030043-63ca505a-f61f-4433-9745-19bb67f8d804.mov

**Comment by felipetesc** [comment]
I have a different bug when I run your code on Linux, once I click the button I get:
```bash
╭─ftx@FTX in /run/media/ftx/HD1T/Projects/Python/CtkProjects/CtkCookbook/bugs via  v3.10.4 took 587ms
 ╰─λ python bug_open_tab.py                                                                        
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/run/media/ftx/HD1T/Projects/Python/CustomTkinter/customtkinter/widgets/ctk_combobox.py", l
ine 300, in clicked
    self.open_dropdown_menu()
  File "/run/media/ftx/HD1T/Projects/Python/CustomTkinter/customtkinter/widgets/ctk_combobox.py", l
ine 176, in open_dropdown_menu
    self.dropdown_menu = DropdownMenu(x_position=self.winfo_rootx(),
  File "/run/media/ftx/HD1T/Projects/Python/CustomTkinter/customtkinter/widgets/dropdown_menu.py", 
line 81, in __init__
    self.wm_attributes("-transparentcolor", "#010302")
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2005, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: bad attribute "-transparentcolor": must be -alpha, -topmost, -zoomed, -fullscree
n, or -type
```
When I comment the line 81, the the result is as showed as below:

![open_tab_on_click_dropdown](https://user-images.githubusercontent.com/2336812/172032476-7acbc8de-d7fb-4d6e-85f3-acd4b6bd7cdd.gif)

**Comment by wassafshahzad** [comment]
I tested this out on windows and seems to be working fine.

**Comment by Naatan** [comment]
fwiw my repro was on macOS Monterey.

**Comment by TomSchimansky** [comment]
It's working fine now with version 4.4.0. I use a normal tkinter.Menu now.
