### ISSUE TITLE
CTk 5.1.3: KeyError when theming CTkRadioButton

### ISSUE THREAD

**Issue by dishb** [TomSchimansky/CustomTkinter#1665]
**Traceback:**
```
Traceback (most recent call last):
  File "/Users/dishb/Documents/hive/complex_example.py", line 162, in <module>
    app = App()
          ^^^^^
  File "/Users/dishb/Documents/hive/complex_example.py", line 82, in __init__
    self.radio_button_1 = customtkinter.CTkRadioButton(master=self.radiobutton_frame, variable=self.radio_var, value=0)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/customtkinter/windows/widgets/ctk_radiobutton.py", line 53, in __init__
    self._fg_color = ThemeManager.theme["CTkRadiobutton"]["fg_color"] if fg_color is None else self._check_color_type(fg_color)
                     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'CTkRadiobutton'
```
**Specs:**
macOS: 12.6.6
Python: 3.11.3
CustomTkinter: 5.1.3

**Issue:**

Seems like there's a typo in line 53 of `ctk_radiobutton.py`. This typo leads to a `KeyError` where customtkinter is unable to theme the radio button widget. I'm running the `./examples/complex_example.py` file with a custom theme.

The custom theme (`.json` file) can be downloaded:
[default.json.zip](https://github.com/TomSchimansky/CustomTkinter/files/11585220/default.json.zip)

**Fix:**
I think you only need to fix line 53 in the `ctk_radiobutton.py` file to be:
```python
self._fg_color = ThemeManager.theme["CTkRadioButton"]["fg_color"] if fg_color is None else self._check_color_type(fg_color)
```

**Notes:**
The only line of code I changed in the `complex_example.py` file was line 6, where I set the default color theme to the path to my theme file.

**Comment by dishb** [comment]
Looking at the codebase - this issue seems to have been fixed. I guess just waiting for a PyPI release.

**Comment by dishb** [comment]
I'll just use the Github CTk instead of from PyPI
