### ISSUE TITLE
canot get value text when input CTkInputDialog

### ISSUE THREAD

**Issue by bobwatcherx** [TomSchimansky/CustomTkinter#1722]
my code 
```
import tkinter
import customtkinter 

customtkinter.set_appearance_mode("System")
customtkinter.set_default_color_theme("green")

app = customtkinter.CTk()
app.geometry("400x300")


def button_click_event():
    dialog = customtkinter.CTkInputDialog(text="Type in a number:", title="Test")
    print("Number:", dialog.get_input())


button = customtkinter.CTkButton(app, text="Open Dialog", command=button_click_event)
button.pack(padx=20, pady=20)

app.mainloop()
```

error
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/custometkinter# python3 main.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.10/dist-packages/customtkinter/windows/widgets/ctk_button.py", line 553, in _clicked
    self._command()
  File "/home/miop/belajar/custometkinter/main.py", line 12, in button_click_event
    dialog = customtkinter.CTkInputDialog(text="Type in a number:", title="Test")
  File "/usr/local/lib/python3.10/dist-packages/customtkinter/windows/ctk_input_dialog.py", line 50, in __init__
    self.grab_set()  # make other windows not clickable
  File "/usr/lib/python3.10/tkinter/__init__.py", line 941, in grab_set
    self.tk.call('grab', 'set', self._w)
_tkinter.TclError: grab failed: window not viewable

**Comment by TomSchimansky** [comment]
What platform are you using, Linux?

**Comment by avalon60** [comment]
Hello @bobwatcherx. I'm on Linux Mint and that runs fine. I am on 21.1 and that runs fine for me. 

![image](https://github.com/TomSchimansky/CustomTkinter/assets/89534395/6f4e3fae-108f-40a0-8775-0bb3086a67fd)

Unless you have manually upgraded Python, I am guessing that you are on Linux Mint 21.1 also. Anyhow, here is what I get:

![image](https://github.com/TomSchimansky/CustomTkinter/assets/89534395/6d510fa0-d842-4f83-b33d-65e1b44b9be6)

![image](https://github.com/TomSchimansky/CustomTkinter/assets/89534395/03f92154-0d05-4008-a7a6-5421be1c61ae)

When I enter a number, and click on the OK button, I get the entered number output to the console:

![image](https://github.com/TomSchimansky/CustomTkinter/assets/89534395/2bf8770a-a2f4-46af-87e8-6f583f48f20f)

**Comment by bobwatcherx** [comment]
why is it still not working on me and i using Awesome WM in Linux Min

```
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/fletsub2# pip list | grep customtkinter
customtkinter            5.1.3

root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/fletsub2# python3 --version
Python 3.10.6
```


![Selection_003](https://github.com/TomSchimansky/CustomTkinter/assets/52072811/ed8d6e04-bf0d-4337-8953-a16c0b8c340e)

**Comment by bobwatcherx** [comment]
i remove code import tkinter

**Comment by bobwatcherx** [comment]
full code 
```
import customtkinter 

customtkinter.set_appearance_mode("System")
customtkinter.set_default_color_theme("green")

app = customtkinter.CTk()
app.geometry("400x300")


def button_click_event():
    dialog = customtkinter.CTkInputDialog(text="Type in a number:", title="Test")
    print("Number:", dialog.get_input())


button = customtkinter.CTkButton(app, text="Open Dialog", command=button_click_event)
button.pack(padx=20, pady=20)

app.mainloop()
```

**Comment by bobwatcherx** [comment]
you can try using Awesome WM . i get Errror

**Comment by TomSchimansky** [comment]
you can try it with normal tkinter to verify its a CustomTkinter issue

**Comment by kondamo1806** [comment]
The same here
