### ISSUE TITLE
Unhandled exception in scritp

### ISSUE THREAD

**Issue by Aminestesnaei** [TomSchimansky/CustomTkinter#1723]
Failed to execute script 'main.py' due to unhandled exception 'CTk'

Traceback (most recent call last):
  File "main.py", line 209, in <module>
  File "main.py", line 135, in root
  File "customtkinter\windows\ctk_tk.py", line 51, in __init__
    super().configure(bg=ThemeManager.single_color(self.fg_color, self.appearance_mode))
KeyError: 'CTk'

**Comment by TomSchimansky** [comment]
If you have an error please refer to Discussions and provide a full example code.
