### ISSUE TITLE
CTk v 5.1.3: Exception when destroying app via a thread.

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#1733]
I am wanting to close down an app, via a thread, but I get an exception.

I have reproduced this on a smaller scale. With a larger app (complex_example.py sized), it occurs more frequently (almost every time).  In this example I had to run it about 6-7 times to cause the exception.

This small app closes itself down after a short delay (3 second).

Here is the code:
```
import customtkinter as ctk
import threading
import time

class App(ctk.CTk):
    def __init__(self):
        super().__init__()

        self.geometry("400x300")
        button = ctk.CTkButton(self, text="Quit", command=self.close_app)
        button.pack(padx=20, pady=20)
        self.delayed_quit()

        self.mainloop()

    def delayed_quit(self):
        client_thread = threading.Thread(target=self.delayed_close_app,
                                         daemon=True)
        client_thread.start()

    def delayed_close_app(self):
        time.sleep(3)
        self.close_app()

    def close_app(self):
        self.destroy()

if __name__ == "__main__":
    app = App()
```

Here is the exception:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py", line 188, in _update_dimensions_event
    self._draw(no_color_updates=True)  # faster drawing without color changes
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_button.py", line 194, in _draw
    self._canvas.delete("background_parts")
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2852, in delete
    self.tk.call((self._w, 'delete') + args)
_tkinter.TclError: invalid command name ".!ctkbutton.!ctkcanvas"
```
Any ideas?

**Comment by ElectricCandlelight** [comment]
Don't do any tkinter operations from a different thread. Instead use a custom event, using event_generate() that triggers a function in the main thread running tkinter

**Comment by avalon60** [comment]
> event_generate

Hi @ElectricCandlelight. Can you explain a little further how this is done? 
Thanks.

**Comment by TomSchimansky** [comment]
Tkinter is not thread safe, but that's how I would do it:
```python
import customtkinter as ctk
import threading
import time


class App(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.geometry("400x300")
        self.running = True

        button = ctk.CTkButton(self, text="Quit", command=self.close_app)
        button.pack(padx=20, pady=20)

        self.delayed_quit()
        self.after(100, self.check_for_running)
        self.mainloop()

    def check_for_running(self):
        if not self.running:
            self.close_app()
        else:
            self.after(100, self.check_for_running)

    def delayed_quit(self):
        client_thread = threading.Thread(target=self.delayed_close_app, daemon=True)
        client_thread.start()

    def delayed_close_app(self):
        time.sleep(3)
        self.running = False

    def close_app(self):
        self.destroy()


if __name__ == "__main__":
    app = App()

```

**Comment by avalon60** [comment]
Thanks @TomSchimansky
