### ISSUE TITLE
CTk 5.2.0: Intermittent exceptions, following CustomTkinter upgrade

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#1752]
Since upgrading to CustomTkinter 5.2.0, I have noticed occasional failures when I launch the QA app (based on complex_example.py) from my theme builder.

None of the error stack points to the QA app, so it's hard to know where to start from my end. Here is the error stack:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py", line 188, in _update_dimensions_event
    self._draw(no_color_updates=True)  # faster drawing without color changes
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_switch.py", line 212, in _draw
    requires_recoloring = self._draw_engine.draw_rounded_slider_with_border_and_button(self._apply_widget_scaling(self._switch_width),
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 900, in draw_rounded_slider_with_border_and_button
    return self.__draw_rounded_slider_with_border_and_button_font_shapes(width, height, corner_radius, border_width, inner_corner_radius,
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 946, in __draw_rounded_slider_with_border_and_button_font_shapes
    requires_recoloring = self.__draw_rounded_progress_bar_with_border_font_shapes(width, height, corner_radius, border_width, inner_corner_radius,
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 773, in __draw_rounded_progress_bar_with_border_font_shapes
    if not self._canvas.find_withtag("progress_oval_1_a"):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2895, in find_withtag
    return self.find('withtag', tagOrId)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2862, in find
    self.tk.call((self._w, 'find') + args)) or ()
_tkinter.TclError: invalid command name ".!ctkframe4.!canvas.!ctkscrollableframe.!ctkswitch31.!ctkcanvas2"
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py", line 188, in _update_dimensions_event
    self._draw(no_color_updates=True)  # faster drawing without color changes
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_switch.py", line 212, in _draw
    requires_recoloring = self._draw_engine.draw_rounded_slider_with_border_and_button(self._apply_widget_scaling(self._switch_width),
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 900, in draw_rounded_slider_with_border_and_button
    return self.__draw_rounded_slider_with_border_and_button_font_shapes(width, height, corner_radius, border_width, inner_corner_radius,
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 946, in __draw_rounded_slider_with_border_and_button_font_shapes
    requires_recoloring = self.__draw_rounded_progress_bar_with_border_font_shapes(width, height, corner_radius, border_width, inner_corner_radius,
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 773, in __draw_rounded_progress_bar_with_border_font_shapes
    if not self._canvas.find_withtag("progress_oval_1_a"):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2895, in find_withtag
    return self.find('withtag', tagOrId)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2862, in find
    self.tk.call((self._w, 'find') + args)) or ()
_tkinter.TclError: invalid command name ".!ctkframe4.!canvas.!ctkscrollableframe.!ctkswitch32.!ctkcanvas2"
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py", line 188, in _update_dimensions_event
    self._draw(no_color_updates=True)  # faster drawing without color changes
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_switch.py", line 212, in _draw
    requires_recoloring = self._draw_engine.draw_rounded_slider_with_border_and_button(self._apply_widget_scaling(self._switch_width),
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 900, in draw_rounded_slider_with_border_and_button
    return self.__draw_rounded_slider_with_border_and_button_font_shapes(width, height, corner_radius, border_width, inner_corner_radius,
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 946, in __draw_rounded_slider_with_border_and_button_font_shapes
    requires_recoloring = self.__draw_rounded_progress_bar_with_border_font_shapes(width, height, corner_radius, border_width, inner_corner_radius,
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 773, in __draw_rounded_progress_bar_with_border_font_shapes
    if not self._canvas.find_withtag("progress_oval_1_a"):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2895, in find_withtag
    return self.find('withtag', tagOrId)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2862, in find
    self.tk.call((self._w, 'find') + args)) or ()
_tkinter.TclError: invalid command name ".!ctkframe4.!canvas.!ctkscrollableframe.!ctkswitch33.!ctkcanvas2"
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py", line 188, in _update_dimensions_event
    self._draw(no_color_updates=True)  # faster drawing without color changes
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_switch.py", line 212, in _draw
    requires_recoloring = self._draw_engine.draw_rounded_slider_with_border_and_button(self._apply_widget_scaling(self._switch_width),
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 900, in draw_rounded_slider_with_border_and_button
    return self.__draw_rounded_slider_with_border_and_button_font_shapes(width, height, corner_radius, border_width, inner_corner_radius,
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 946, in __draw_rounded_slider_with_border_and_button_font_shapes
    requires_recoloring = self.__draw_rounded_progress_bar_with_border_font_shapes(width, height, corner_radius, border_width, inner_corner_radius,
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 773, in __draw_rounded_progress_bar_with_border_font_shapes
    if not self._canvas.find_withtag("progress_oval_1_a"):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2895, in find_withtag
    return self.find('withtag', tagOrId)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2862, in find
    self.tk.call((self._w, 'find') + args)) or ()
_tkinter.TclError: invalid command name ".!ctkframe4.!canvas.!ctkscrollableframe.!ctkswitch34.!ctkcanvas2"
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py", line 188, in _update_dimensions_event
    self._draw(no_color_updates=True)  # faster drawing without color changes
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_switch.py", line 212, in _draw
    requires_recoloring = self._draw_engine.draw_rounded_slider_with_border_and_button(self._apply_widget_scaling(self._switch_width),
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 900, in draw_rounded_slider_with_border_and_button
    return self.__draw_rounded_slider_with_border_and_button_font_shapes(width, height, corner_radius, border_width, inner_corner_radius,
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 946, in __draw_rounded_slider_with_border_and_button_font_shapes
    requires_recoloring = self.__draw_rounded_progress_bar_with_border_font_shapes(width, height, corner_radius, border_width, inner_corner_radius,
  File "/home/clive/PycharmProjects/ctk_theme_builder/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_rendering/draw_engine.py", line 773, in __draw_rounded_progress_bar_with_border_font_shapes
    if not self._canvas.find_withtag("progress_oval_1_a"):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2895, in find_withtag
    return self.find('withtag', tagOrId)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2862, in find
    self.tk.call((self._w, 'find') + args)) or ()
_tkinter.TclError: invalid command name ".!ctkframe4.!canvas.!ctkscrollableframe.!ctkswitch35.!ctkcanvas2"
```
When this happens the QA program usually completely crashes out.
If I retry the launch of the app, the problem usually doesn't manifest itself.

**Comment by dishb** [comment]
Apparently just about every switch _doesn't_ have a `ctk.CTkCanvas` assigned to it. I believe the canvas is how the switches are rendered/drawn to the screen?

**Comment by avalon60** [comment]
Related to an issue previously commented on.
