### ISSUE TITLE
CTk 5.2.0: Exception encountered when configuring CTkSlider, button_corner_radius

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#1790]
The CTkSlider widget does not support the button_corner_radius. From slightly modified complex_example.py:

```
/usr/bin/python3.10 /home/clive/PycharmProjects/research/complex_example.py 
Traceback (most recent call last):
  File "/home/clive/PycharmProjects/research/complex_example.py", line 165, in <module>
    app = App()
  File "/home/clive/PycharmProjects/research/complex_example.py", line 103, in __init__
    self.slider_1.configure(button_corner_radius=0)
  File "/home/clive/.local/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_slider.py", line 258, in configure
    super().configure(require_redraw=require_redraw, **kwargs)
  File "/home/clive/.local/lib/python3.10/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py", line 133, in configure
    check_kwargs_empty(kwargs, raise_error=True)
  File "/home/clive/.local/lib/python3.10/site-packages/customtkinter/windows/widgets/utility/utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['button_corner_radius'] are not supported arguments. Look at the documentation for supported arguments.
```

**Comment by dishb** [comment]
@avalon60 - Could you try again? Looks like Tom introduced a fix in [`9cfd5f4`](https://github.com/TomSchimansky/CustomTkinter/commit/9cfd5f451580d1ddc1a1159cb79db6d64723f4fa)

**Comment by avalon60** [comment]
@dishb what release would this be in?

**Comment by dishb** [comment]
No idea, might be a while until more changes are introduced (some that need to be major).
