### ISSUE TITLE
Deploying with CTK

### ISSUE THREAD

**Issue by OAbdullahs** [TomSchimansky/CustomTkinter#186]
I face an error while trying to deploy my app with **customTkinter** using [PyInstaller](https://pyinstaller.org/en/stable/).

For example, I have this snippet:
 
```
import customtkinter

tk = customtkinter.CTk()

tk.mainloop()
```

Then deploy using the command below:
`python3.10 -m PyInstaller main.py --windowed --onefile`

When running the executable file I receive this error:
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "customtkinter/__init__.py", line 17, in <module>
  File "customtkinter/theme_manager.py", line 16, in load_theme
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/j4/y85zhzsx2ql6h_c2qw1knsr80000gn/T/_MEII8j5Jk/customtkinter/assets/themes/blue.json'
[40031] Failed to execute script 'main' due to unhandled exception: [Errno 2] No such file or directory: '/var/folders/j4/y85zhzsx2ql6h_c2qw1knsr80000gn/T/_MEII8j5Jk/customtkinter/assets/themes/blue.json'
[40031] Traceback:
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "customtkinter/__init__.py", line 17, in <module>
  File "customtkinter/theme_manager.py", line 16, in load_theme
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/j4/y85zhzsx2ql6h_c2qw1knsr80000gn/T/_MEII8j5Jk/customtkinter/assets/themes/blue.json'


Saving session...completed.
```

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging
