### ISSUE TITLE
SegmentedButton  in CTkTabview 

### ISSUE THREAD

**Issue by emcek** [TomSchimansky/CustomTkinter#1880]
SegmentedButton in `CTkTabview` behave differently than `CTkSegmentedButton` itself what is a bit misleading:
## `CTkSegmentedButton`
```python
app = customtkinter.CTk()
def segmented_button_callback(args):
    print("segmented button clicked:", args)
segemented_button = customtkinter.CTkSegmentedButton(app, values=["Value 1", "Value 2", "Value 3"], command=segmented_button_callback)
segemented_button.set("Value 1")
sgemented_button.grid(row=0, column=0)
app.mainloop()
```
## SegmentedButton in `CTkTabview`
```python
app = customtkinter.CTk()
def segmented_button_callback():
    print("segmented button clicked:")
tabview = customtkinter.CTkTabview(master=app, command=segmented_button_callback)
tabview.pack(padx=20, pady=20)
tabview.add("tab 1")  # add tab at the end
tabview.add("tab 2")  # add tab at the end
tabview.set("tab 2")  # set currently visible tab
app.mainloop()
```
In 2nd case `CTkTabview` do not pass current selected button/tab `segmented_button_callback()` no parameters are allowed. If I try use `segmented_button_callback()` like in 1st example, I got:
```
Traceback (most recent call last):
  File "C:\Users\mplic\.pyenv\pyenv-win\versions\3.11.1\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\mplic\Projects\venvs\dcspy_311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\mplic\Projects\venvs\dcspy_311\Lib\site-packages\customtkinter\windows\widgets\ctk_segmented_button.py", line 167, in <lambda>
    command=lambda v=value: self.set(v, from_button_callback=True),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mplic\Projects\venvs\dcspy_311\Lib\site-packages\customtkinter\windows\widgets\ctk_segmented_button.py", line 381, in set
    self._command(self._current_value)
  File "C:\Users\mplic\Projects\venvs\dcspy_311\Lib\site-packages\customtkinter\windows\widgets\ctk_tabview.py", line 107, in _segmented_button_callback
    self._command()
TypeError: segmented_button_callback() missing 1 required positional argument: 'args'
```

**Comment by emcek** [comment]
As workaround I use:
```python
from functools import partial
app = customtkinter.CTk()
def segmented_button_callback(a):
    print(a.get())
tabview = customtkinter.CTkTabview(master=app)
tabview.configure(command=partial(segmented_button_callback, tabview))
tabview.pack(padx=20, pady=20)
tabview.add("tab 1")  # add tab at the end
tabview.add("tab 2")  # add tab at the end
tabview.set("tab 2")  # set currently visible tab

app.mainloop()
```
but append value of `a.get()` (current tab) into callable in `command` parameter of `CTkTabview` would be nice and expected.

**Comment by avalon60** [comment]
It works in a similar way to basic Tkinter. If you wish to pass arguments, you ha e to use a lambda function.
See [Passing functions with Parameters in Tkinter using Lambda](https://pythonprogramming.net/passing-functions-parameters-tkinter-using-lambda/)

**Comment by emcek** [comment]
> The command parameter works in a similar way to Tkinter. If you wish to pass arguments, you have to use a lambda function. See [Passing functions with Parameters in Tkinter using Lambda](https://pythonprogramming.net/passing-functions-parameters-tkinter-using-lambda/)

I know that, but prefer `partial()`. I was taking that `CTkSegmentedButton` add parameter automatically to callable of `command=` (See 1st example)
