### ISSUE TITLE
customtkinter.CTkComboBox too many values?

### ISSUE THREAD

**Issue by SwaggerNiels** [TomSchimansky/CustomTkinter#195]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "~\Programs\Python\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "~\Programs\Python\Python39\lib\site-packages\customtkinter\widgets\ctk_combobox.py", line 300, in clicked
    self.open_dropdown_menu()
  File "~\Programs\Python\Python39\lib\site-packages\customtkinter\widgets\ctk_combobox.py", line 176, in open_dropdown_menu
    self.dropdown_menu = DropdownMenu(x_position=self.winfo_rootx(),
  File "~\Programs\Python\Python39\lib\site-packages\customtkinter\widgets\dropdown_menu.py", line 103, in __init__
    button.text_label.configure(anchor="w")
```

This happens when I call a `customtkinter.CTkComboBox` with too many options.
Probably related to the scrolling feature that is integrated in tkinter combobox when there are many options.

Related question:
- Is there a way to flip the dropdown menu upwards or have a better way to select value in long lists?

**Comment by TomSchimansky** [comment]
Please update the library and try again, I completely removed the custom dropdown menu, because of too many bugs. I use a normal tkinter.Menu now instead.

**Comment by SwaggerNiels** [comment]
Works fine now!
