### ISSUE TITLE
Problem in theme_manager

### ISSUE THREAD

**Issue by MiKalem898** [TomSchimansky/CustomTkinter#1983]
I'm coding an app with the package and when I want to start the script as an executable file (I use pyinstaller), I get this error:
*`Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\__init__.py", line 20, in <module>
    # import widgets
  File "customtkinter\theme_manager.py", line 25, in load_theme
    cls.theme["text"] = cls.theme["text"]["Windows"]
KeyError: 'text'`

I don't understand why I got this because in my other projects I didn't get this error

**Comment by MiKalem898** [comment]
It's better in picture
![image](https://github.com/TomSchimansky/CustomTkinter/assets/92682827/b905f12d-7efb-4947-9f5a-f83586358be0)

**Comment by bfedie518** [comment]
CTk doesn't always play nice with PyInstaller.  Did you follow the instructions here?
https://customtkinter.tomschimansky.com/documentation/packaging

**Comment by MiKalem898** [comment]
> CTk doesn't always play nice with PyInstaller. Did you follow the instructions here? https://customtkinter.tomschimansky.com/documentation/packaging

Yes, I did that but the error still exists

**Comment by ahad-naseer-innusagi** [comment]
@MiKalem898 can you show your code or command of pyinstaller for proper guidance?

**Comment by MiKalem898** [comment]
> @MiKalem898 can you show your code or command of pyinstaller for proper guidance?

Sry I didn't show ur answer

I do that often and it works ??
`pyinstaller --add-data "c:/users/mikal/pycharmprojects/klink-python/venv/lib/site-packages/customtkinter;customtkinter/"  main.py `
