### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by Endkind** [TomSchimansky/CustomTkinter#2137]
I am encountering a recurring issue where, regardless of whether I insert tutorials or use examples, I consistently face the following error.

Code:
```python
import customtkinter as ctk

window = ctk.CTk()
window.title('customtkinter app')
window.geometry('600x400')

window.mainloop()
```

Console:
```bash
/home/endkind/projects/test/venv/bin/python /home/endkind/projects/test/app.py 
Traceback (most recent call last):
  File "/home/endkind/projects/test/app.py", line 1, in <module>
    import customtkinter as ctk
  File "/home/endkind/projects/test/venv/lib/python3.10/site-packages/customtkinter/__init__.py", line 5, in <module>
    from tkinter import Variable, StringVar, IntVar, DoubleVar, BooleanVar
ModuleNotFoundError: No module named 'tkinter'

Process finished with exit code 1

```

**Comment by Endkind** [comment]
After discovering and executing the command `apt-get install python3-tk`, the issue has been resolved, and the functionality is now working as expected.
