### ISSUE TITLE
mainloop throwing error

### ISSUE THREAD

**Issue by BhagyaJyoti22006** [TomSchimansky/CustomTkinter#2233]
I want to create a splash screen. in tkinter i can just call tkinter.mainloop() to run any added window. However ctk throws error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\py\code.py", line 77, in <module>
    ctk.mainloop()
    ^^^^^^^^^^^^
AttributeError: module 'customtkinter' has no attribute 'mainloop'

**Comment by Anonymous6598** [comment]
Show full code please
