### ISSUE TITLE
CTkTabview - cannot change name of open tab

### ISSUE THREAD

**Issue by mikolaj-rokicki** [TomSchimansky/CustomTkinter#2277]
Hi,

I've noticed that you cannot change a name of currently opened tab of CTkTabview by rename function.
It responds with errors:

_

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
>     return self.func(*args)
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\mikol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
>     self._command()
>   File "C:\Users\mikol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\customtkinter\windows\widgets\ctk_segmented_button.py", line 167, in <lambda>
>     command=lambda v=value: self.set(v, from_button_callback=True),
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\mikol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\customtkinter\windows\widgets\ctk_segmented_button.py", line 381, in set
>     self._command(self._current_value)
>   File "C:\Users\mikol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\customtkinter\windows\widgets\ctk_tabview.py", line 104, in _segmented_button_callback
>     self._tab_dict[self._current_name].grid_forget()

_

Although its not severe issue, couse one can still change name when tab is inactive

**Comment by its-joseph-230606** [comment]
**Can you please provide the source code?**
