### ISSUE TITLE
No CTkTreeView?

### ISSUE THREAD

**Issue by adamtcdev** [TomSchimansky/CustomTkinter#2357]
CustomTkinter is a good and modern GUI and it's a fit for my project. But there's only one thing. I don't see any Treeview here. Anyone help? I already saw #524 but I don't know how to put the light/dark callback (AppearanceModeTracker.add(callback)) and use it with scale:
```python
  File "g:\My Drive\TinEdu\v0.2-0304-beta\main.py", line 21, in __init__
    text_font = self._apply_appearance_mode(ThemeManager.theme["CTkLabel"]["font"])
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'font'
```

Anyone help?

**Comment by adamtcdev** [comment]
https://stackoverflow.com/questions/78283327/is-there-any-ctktreeview-in-customtkinter

**Comment by Akascape** [comment]
@adamtcdev Why are you using `self._apply_appearance_mode` method? It is only for distinguishing colors which are in tuple form. You simply use `text_font = ThemeManager.theme["CTkFont"]["family"]`

**Comment by JanPanthera** [comment]
There is no official TreeView, but you can use my TreeView and use/adapt how you like it😹
https://github.com/JanPanthera/_GuiFramework/tree/main/GuiFramework/widgets/tree_view

**Comment by adamtcdev** [comment]
> There is no official TreeView, but you can use my TreeView and use/adapt how you like it😹 https://github.com/JanPanthera/_GuiFramework/tree/main/GuiFramework/widgets/tree_view
> 
> Edit: Here an example where i use it https://github.com/JanPanthera/_AutodriveTranslationTool/blob/main/AutoDriveTranslationTool/src/components/dictionary_frame/dictionary_frame_gui.py

I am not sure about it...

```
WARNING: Skipping GuiFramework as it is not installed.
Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\_GuiFramework-main\setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
The system cannot find the file specified.
ERROR: Invalid requirement: 'dist\\'
Hint: It looks like a path. File 'dist\' does not exist.
Press any key to continue . . .
```

**Comment by JanPanthera** [comment]
yeah thats old, sorry the setup is not working instead you can use the update_package.bat, but this essential reinstalls every needed library, don't recommend that if you have made any changes to your ctk, if you haven't made any changes to customtkinter use it to install the GuiFramework in to your python shared libs. if someone wants to help me get a nice setup working, please help me xD

**Comment by adamtcdev** [comment]
https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by JanPanthera** [comment]
> Oh, and did anyone know how to set the default font in CTk?

you can do that by edit one of the default themes or by creating a custom theme and load that.
here is a genereal guide, if you need more help i can try to help, its a bit since i played with custom themes ;-)
[Themes](https://github.com/TomSchimansky/CustomTkinter/wiki/Themes)

**Comment by adamtcdev** [comment]
> @adamtcdev Why are you using `self._apply_appearance_mode` method? It is only for distinguishing colors which are in tuple form. You simply use `text_font = ThemeManager.theme["CTkFont"]["family"]`

I am wondering if we could make a tuple like this.
```python
text_font = ThemeManager.theme["CTkFont"]["family"]
text_size = ThemeManager.theme["CTkFont"]["size"]
text_tuple =  (text_font, text_size)
```
And put it in the Treeview: 
```python
treestyle.configure("Treeview", background=bg_color, foreground=text_color, fieldbackground=bg_color, font=text_tuple, borderwidth=0)
```

**Comment by JanPanthera** [comment]
you mean the tkinter treeview?
I'm not sure how styling works in plain tkinter, but can take a look.It looks interesting
