### ISSUE TITLE
iconphoto is not working

### ISSUE THREAD

**Issue by adamtcdev** [TomSchimansky/CustomTkinter#2387]
code:
```python
class root(CTk):
    def __init__(self):
        super().__init__()
        set_widget_scaling(1.2)

        self.title("TinEdu")
        self.geometry('1200x720')
        self.iconphoto(1, PhotoImage('.\\icons\\tiny_logo.png'))
```

output:
```python
Traceback (most recent call last):
  File "g:\My Drive\TinEdu\v0.2-0304-beta\main.py", line 157, in <module>
    root = root()
           ^^^^^^
  File "g:\My Drive\TinEdu\v0.2-0304-beta\main.py", line 16, in __init__
    self.iconphoto(1, PhotoImage('.\\icons\\tiny_logo.png'))
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 2200, in wm_iconphoto
    self.tk.call('wm', 'iconphoto', self._w, "-default", *args)
_tkinter.TclError: failed to create an iconphoto with image ".\icons\tiny_logo.png"
```

**Comment by Akascape** [comment]
@adamtcdev 
**Try this method:**

`For root window:`
```python
import os
from PIL import ImageTk
...

self.iconpath = ImageTk.PhotoImage(file=os.path.join("assets","logo.png"))
self.wm_iconbitmap()
self.iconphoto(False, self.iconpath)
```
`For toplevels:`
```python
self.wm_iconbitmap()
self.after(300, lambda: self.iconphoto(False, self.iconpath))
```

**Comment by adamtcdev** [comment]
Thanks.

**Comment by adamtcdev** [comment]
I am gonna close this issue.
