### ISSUE TITLE
Cannot configure image in widgets after the latest update

### ISSUE THREAD

**Issue by Akascape** [TomSchimansky/CustomTkinter#251]
I was not updating the module after the removal of combobox's dropdown menu, but after working on a new project with the latest version I am facing some trouble,
I got a recurring error when I use the configure method to change the widget image
```python
button.configure(image=new_image)
```
Error:
```
Traceback (most recent call last):
  File "app.py", line 105, in <module>
    button.configure(image=new_image)
  File "E:\Python\lib\site-packages\customtkinter\widgets\ctk_button.py", line 253, in configure
    self.set_image(self.image)
  File "E:\Python\lib\site-packages\customtkinter\widgets\ctk_button.py", line 307, in set_image
    self.configure(image=image)
  File "E:\Python\lib\site-packages\customtkinter\widgets\ctk_button.py", line 253, in configure
    self.set_image(self.image)
...
  File "E:\Python\lib\site-packages\customtkinter\widgets\ctk_button.py", line 253, in configure
    self.set_image(self.image)
  52, in configure
    self.image = kwargs.pop("image")
  RecursionError: maximum recursion depth exceeded while calling a Python object 
```

Don't know why this is happening, any fix? 
Also tried with my previous app, getting the same error.

**Comment by TomSchimansky** [comment]
Should be fixed now with 4.5.5
