### ISSUE TITLE
Window icon impossible to change

### ISSUE THREAD

**Issue by Docteur-No** [TomSchimansky/CustomTkinter#2654]
I use since a year a customtkinter python script which worked very well till now.
I have to make some improvements and it don't works due to icon change while there was no problem until then.
I tried various methods found on the web, none of them work!!!

My code : 
`app = ctk.CTk()

app.title('TLALOC Arrosage')

app.geometry('550x650+1000+50')

app.resizable(width=0, height=0)

**app.iconbitmap('Arrosoir.ico')**`

Return :
`PS C:\Users\monsh> & C:/Users/monsh/AppData/Local/Microsoft/WindowsApps/python3.12.exe c:/Users/monsh/OneDrive/Domotique/0-GUI_Pisc/Arrosage.py
Subscribed: 2 (0,)
19:19:24
Traceback (most recent call last):
  File "c:\Users\monsh\OneDrive\Domotique\0-GUI_Pisc\Arrosage.py", line 303, in <module>
    app.iconbitmap('Arrosoir.ico')
  File "C:\Users\monsh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\customtkinter\windows\ctk_tk.py", line 232, in iconbitmap
    super().wm_iconbitmap(bitmap, default)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 2156, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "Arrosoir.ico" not defined`

I tried to use a png, impossible to make it work too
I really don't know what could I do

**Comment by dipeshSam** [comment]
Check out similar solved issue: https://github.com/TomSchimansky/CustomTkinter/issues/2387

**Comment by Docteur-No** [comment]
YES, it works using Pillow
Many thanks
