### ISSUE TITLE
Is config and configure different in CTkSlider ?

### ISSUE THREAD

**Issue by ghanteyyy** [TomSchimansky/CustomTkinter#270]
When I used `config` in `CTkSlider`

```python
from tkinter import *
from customtkinter import CTkSlider

root = Tk()

slider = CTkSlider(master=root, from_=0, to=100)   # Works to parameter here
slider.pack()

root.after(1000, lambda: slider.config(to=200))
root.mainloop()
```

I got the following error:

```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\6292s\Desktop\My Projects\nppy\PROJECT GUIs\MUSIC PLAYER\MusicPlayer.py", line 665, in PlayOrPauseAudio
    raise e
  File "C:\Users\6292s\Desktop\My Projects\nppy\PROJECT GUIs\MUSIC PLAYER\MusicPlayer.py", line 599, in PlayOrPauseAudio
    self.AudioSlider.config(to=int(self.TotalTime))    # Problem is coming from this one
  File "C:\Python310\lib\tkinter\__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Python310\lib\tkinter\__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-to" 
```

But when I used `configure` in `CTkSlider`

```python
from tkinter import *
from customtkinter import CTkSlider

root = Tk()

slider = CTkSlider(master=root, from_=0, to=100)   # Works to parameter here
slider.pack()

root.after(1000, lambda: slider.configure(to=200))
root.mainloop()
```

**It works fine!!**

**Comment by TheFallen-Cat** [comment]
As far as i know, config and configure is loterally the same thing in tkinter, so it is probably a bug @ghanteyyy

**Comment by TomSchimansky** [comment]
Only .configure() is implemented in CustomTkinter, .config() does not work at the moment. Maybe I will add this.
