### ISSUE TITLE
dpi_scaling - TclError: bad screen distance

### ISSUE THREAD

**Issue by luizcbarros** [TomSchimansky/CustomTkinter#323]
I have received this error over and over again.
I would like to know how it is possible to solve this error.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\user\Anaconda3\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "C:\Users\user\Anaconda3\lib\site-packages\customtkinter\scaling_tracker.py", line 171, in check_dpi_scaling
    cls.update_scaling_callbacks_for_window(window)
  File "C:\Users\user\Anaconda3\lib\site-packages\customtkinter\scaling_tracker.py", line 76, in update_scaling_callbacks_for_window
    set_scaling_callback(cls.window_dpi_scaling_dict[window] * cls.widget_scaling,
  File "C:\Users\user\Anaconda3\lib\site-packages\customtkinter\widgets\ctk_frame.py", line 68, in set_scaling
    self.canvas.configure(width=self.apply_widget_scaling(self._desired_width), height=self.apply_widget_scaling(self._desired_height))
  File "C:\Users\user\Anaconda3\lib\tkinter\__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\user\Anaconda3\lib\tkinter\__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: bad screen distance "180.0"
```

**Comment by TomSchimansky** [comment]
Please also post a small example code that produces this error. And what platform are you using and which python version?

**Comment by felipetesc** [comment]
Do this error remains if you use CustomTkinter without Anaconda ?
