### ISSUE TITLE
AttributeError: partially initialized module 'customtkinter' has no attribute 'set_appearance_mode' (most likely due to a circular import)

### ISSUE THREAD

**Issue by clawjelly** [TomSchimansky/CustomTkinter#447]
When i run the demo script, 

``` python
import tkinter
import customtkinter

customtkinter.set_appearance_mode("System")  # Modes: system (default), light, dark
customtkinter.set_default_color_theme("blue")  # Themes: blue (default), dark-blue, green

app = customtkinter.CTk()  # create CTk window like you do with the Tk window
app.geometry("400x240")

def button_function():
    print("button pressed")

# Use CTkButton instead of tkinter Button
button = customtkinter.CTkButton(master=app, text="CTkButton", command=button_function)
button.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)

app.mainloop()
```

i get this:

```
Traceback (most recent call last):
  File "C:\Users\clawj\SynologyDrive\Private\Python\Modules\Tkinter\customtkinter.py", line 2, in <module>
    import customtkinter
  File "C:\Users\clawj\SynologyDrive\Private\Python\Modules\Tkinter\customtkinter.py", line 4, in <module>
    customtkinter.set_appearance_mode("System")  # Modes: system (default), light, dark
AttributeError: partially initialized module 'customtkinter' has no attribute 'set_appearance_mode' (most likely due to a circular import)
[Finished in 132ms]
```

**Comment by Akascape** [comment]
@clawjelly This is most likely because you have named your python(.py) file as `customtkinter.py` which is confusing itself from the customtkinter module.

**Comment by clawjelly** [comment]
Oh... lol... Alright, thanks, it works after renaming the file.
