### ISSUE TITLE
_tkinter.TclError: bad screen distance "180.0"

### ISSUE THREAD

**Issue by famko09** [TomSchimansky/CustomTkinter#494]
Hi , when I add this line " from ttkbootstrap.constants import *" into CustomTkinterLibrary.py I 'll get this error:

Would like some help to solve this..
Thank you

Traceback (most recent call last):
  File "d:\pcloud\python\tkinter\CustomTkinterLibrary6.py", line 211, in <module>
    app = App()
  File "d:\pcloud\python\tkinter\CustomTkinterLibrary6.py", line 35, in __init__
    self.frame_left = customtkinter.CTkFrame(master=self,width=test_width, corner_radius=0)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38\lib\site-packages\customtkinter\widgets\ctk_frame.py", line 41, in __init__
    self.canvas = CTkCanvas(master=self,
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38\lib\site-packages\customtkinter\widgets\ctk_canvas.py", line 10, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38\lib\site-packages\ttkbootstrap\style.py", line 5142, in __init__wrapper
    func(self, *args, **kwargs)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 2688, in __init__
    Widget.__init__(self, master, 'canvas', cnf, kw)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: bad screen distance "180.0"

**Comment by TomSchimansky** [comment]
I don't know what ttkbootstrap does, why would you import it?

**Comment by famko09** [comment]
It's a set of circular progressbars......

**Comment by famko09** [comment]
don't wast any time, found a working alternative: https://pypi.org/project/AwesomeTkinter/
