### ISSUE TITLE
the library is not working with pyinstaller

### ISSUE THREAD

**Issue by tomh751** [TomSchimansky/CustomTkinter#52]
i tried to create an EXE file with the library but when i import it in the code, i can't run the app since its giving me the error such as in the picture (i'll add the full traceback error). is there a problem with using it outside of the python environment?
Traceback (most recent call last):
  File "app_try.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\widgets\customtkinter_input_dialog.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\widgets\customtkinter_label.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\widgets\customtkinter_tk.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\customtkinter_theme_manager.py", line 83, in <module>
  File "customtkinter\customtkinter_theme_manager.py", line 16, in load_theme
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Local\\Temp\\_MEI99762\\customtkinter\\assets\\themes\\blue.json'

<img width="301" alt="image" src="https://user-images.githubusercontent.com/86208159/166253076-ea977254-4d29-4abd-91b6-5fe9e90fb939.png">

**Comment by TomSchimansky** [comment]
This is a known problem. It's actually a pyinstaller problem, because pyinstaller does not include datafiles from library folders in the .exe folder. So you have to include the customkinter folder manually. Instructions can be found in the wiki:
https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging

**Comment by tomh751** [comment]
i tried to put the directory of the script to add the data of customtkinter but it says this: "PermissionError: [Errno 13] Permission denied:".
any idea why?

**Comment by TomSchimansky** [comment]
Im not familiar with the Windows console, maybe you can try to use Auto-PyToExe, where you do the compilation with a user interface. Otherwise you would have to change the read permission of the customtkinter library folder. Or try to copy the folder to another location by hand in the file explorer, and then use the copied version.
