### ISSUE TITLE
CTkScrollbar KeyError

### ISSUE THREAD

**Issue by James46113** [TomSchimansky/CustomTkinter#746]
Trying to use the CTkScrollbar and I'm getting this error. It works with the default tkinter scrollbar:
```
Traceback (most recent call last):
  File "/home/james/file_explorer/gui_main.py", line 44, in <module>
    sb = CTkScrollbar(tk, command=c.yview)
  File "/home/james/file_explorer/.env/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_scrollbar.py", line 52, in __init__
    self._button_color = ThemeManager.theme["CTkScrollbar"]["scrollbar_color"] if button_color is None else self._check_color_type(button_color)
KeyError: 'scrollbar_color'
```

**Comment by James46113** [comment]
Missed earlier issues that said it will get fixed soon
