### ISSUE TITLE
Running .exe file converted using pyinstaller returns an error

### ISSUE THREAD

**Issue by anhduc261209** [TomSchimansky/CustomTkinter#76]
I just convert the .py file using pyinstaller (normally, no --onefile or --onedir whatsoever)
And it reutrns this error
![image](https://user-images.githubusercontent.com/96221801/168097048-9d8e3077-da38-4ac8-9f79-299fd2de643d.png)
Here is the full log:
Traceback (most recent call last):
  File "test.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\widgets\customtkinter_input_dialog.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\widgets\customtkinter_label.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\widgets\customtkinter_tk.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\customtkinter_theme_manager.py", line 83, in <module>
  File "customtkinter\customtkinter_theme_manager.py", line 16, in load_theme
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\anhdu\\AppData\\Local\\Temp\\_MEI106562\\customtkinter\\assets\\themes\\blue.json'

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging
