### ISSUE TITLE
CTkImage on setting inside a label throws (_tkinter.TclError: image "pyimage4" doesn't exist) error

### ISSUE THREAD

**Issue by TriDEntApollO** [TomSchimansky/CustomTkinter#822]
```python
class EyeButton:
    def __init__(self, master: customtkinter.CTkEntry, hide_char: str):
        self.master = master
        self.hide_char = hide_char
        self.unhide = customtkinter.CTkImage(dark_image=Image.open("Eye.png"), size=(22, 18))
        self.hide = customtkinter.CTkImage(dark_image=Image.open("NotEye.png"), size=(24, 20))
        self.buttonLabel = customtkinter.CTkLabel(master=self.master, font=('Roboto', 12), text='', image=self.unhide, fg_color='transparent', height=self.master.winfo_height()-10)
        self.buttonLabel.image = self.unhide

    def initialize(self):
        self.buttonLabel.bind("<Button-1>", lambda e: self.state())
        self.buttonLabel.place(relx=0.99, rely=0.5, anchor='e')
        self.tracker = 1

    def state(self):
        if self.tracker == 1:
            self.master.configure(show="")
            self.buttonLabel.configure(image=self.hide)
            self.tracker = False
        else:
            self.master.configure(show=self.hide_char)
            self.buttonLabel.configure(image=self.unhide)
            self.tracker = True
        self.tracker *= 1


def login_box():
    ConnectionWin.after(200, lambda: threading.Thread(target=ConnectionWin.destroy).start())
    box = customtkinter.CTk()
    box.title("PyChat Login")
    box.iconbitmap('PyChat.ico')
    w = 400
    h = 410
    box.geometry(get_geo(box, w, h))
    frame = customtkinter.CTkFrame(master=box)
    frame.pack(pady=20, padx=40, fill="both", expand=True)
    uname = customtkinter.CTkEntry(master=frame, placeholder_text="Username", width=240)
    uname.pack(pady=12, padx=10)
    passwd = customtkinter.CTkEntry(master=frame, placeholder_text="Password", show="•", width=240)
    passwd.pack(pady=12, padx=10)
    box.update()
    showButton = EyeButton(master=passwd, hide_char="•") #Getting error while creating child
    showButton.initialize()
    LoginButton = customtkinter.CTkButton(master=frame, text="Sign in", command=login)
    LoginButton.pack(pady=12, padx=10)
    box.update()
    box.mainloop()
```

The class is used to create a eye button that hides and unhides password inside the CTkEntry box. Previously it used to work fine unless i added a loading screen before the login screen that gets destroyed inside the login_box function via a thread (the ConnectionWin) but since the button is initilized before the window gets destroyed it trows the following error.

```error
Traceback (most recent call last):
  File "C:\Users\Rishi\PycharmProjects\PyChat\test.py", line 253, in connect
    login_box()
  File "C:\Users\Rishi\PycharmProjects\PyChat\test.py", line 180, in login_box
    showButton = EyeButton(master=passwd, hide_char="•")
  File "C:\Users\Rishi\PycharmProjects\PyChat\test.py", line 16, in __init__
    self.buttonLabel = customtkinter.CTkLabel(master=self.master, font=('Roboto', 12), text='', image=self.unhide, fg_color='transparent', height=self.master.winfo_height()-10)
  File "C:\Users\Rishi\PycharmProjects\PyChat\venv\lib\site-packages\customtkinter\windows\widgets\ctk_label.py", line 93, in __init__
    self._update_image()
  File "C:\Users\Rishi\PycharmProjects\PyChat\venv\lib\site-packages\customtkinter\windows\widgets\ctk_label.py", line 130, in _update_image
    self._label.configure(image=self._image.create_scaled_photo_image(self._get_widget_scaling(),
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: image "pyimage4" doesn't exist
```

I tried decreasing the after() time for destroying the window but that results in another RuntimError mainthread is not inside mainloop and i also tried to disable the garbage collector so that it doesnt collect the vraible data and clear it by doing `g.disable()` and checked the gc state by `gc.isenabled()` which returned false but still the same error.

**Comment by Swastik2442** [comment]
I am having the same error while running the code on a Jupyter Notebook, it works fine on a normal .py file.
Any solution?

**Comment by TriDEntApollO** [comment]
I still haven't found any fix to the issue but i have seen this issue
mostly occurs on Spyder or Jupiter notebook it's something with the
ide/editor using their own shell rather use the global system
shell/terminal

This probably won't be of much help but you can try also the issue is
raised only when a previous window was created but not destroyed so you
could try destroying the previous window first as tkinter only allows one
root window at a time.

**Comment by TriDEntApollO** [comment]
Did it help?
