### ISSUE TITLE
CTkScrollbar not working

### ISSUE THREAD

**Issue by Melih61** [TomSchimansky/CustomTkinter#829]
Hey,
i tried to use CTkScrollbar in my project but there was an error

i used the example from [https://github.com/TomSchimansky/CustomTkinter/wiki/CTkScrollbar](https://github.com/TomSchimansky/CustomTkinter/wiki/CTkScrollbar)

but there is still the same error

```
Traceback (most recent call last):
  File "c:\Users\fortniteballs\Desktop\a.py", line 12, in <module>
    ctk_textbox_scrollbar = customtkinter.CTkScrollbar(app, command=tk_textbox.yview)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fortniteballs\AppData\Roaming\Python\Python311\site-packages\customtkinter\windows\widgets\ctk_scrollbar.py", line 52, in __init__
    self._button_color = ThemeManager.theme["CTkScrollbar"]["scrollbar_color"] if button_color is None else self._check_color_type(button_color)
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'scrollbar_color'
```

**Comment by TomSchimansky** [comment]
Hi, you have to update your version, this issue was already fixed.
