### ISSUE TITLE
module 'customtkinter' has no attribute 'CTkSwitch' & 'CTkRadioButton'

### ISSUE THREAD

**Issue by NoobGamesDev** [TomSchimansky/CustomTkinter#83]
**Describe the bug**
As mentioned in the title, two attributes are missing. 
I have found differences inside my folder, and the current GitHub Widgets directory.

Mine:
![image](https://user-images.githubusercontent.com/20015201/168671109-158f1761-8983-45f4-967f-a55236084f3c.png)

Github:
![image](https://user-images.githubusercontent.com/20015201/168671191-42e0690c-e008-46c0-879a-1d1143b3d433.png)

I've got it working when both these attributes are not used in the code. Just so you know :)

**Steps to reproduce the behavior:**
install CustomTkinter inside PyCharm venv via the Python Packages manager (customtkinter 2.4 is installed).
![image](https://user-images.githubusercontent.com/20015201/168670712-1142c122-d1f7-4477-9401-d139583f69a0.png)

Copy the code from "complex_example.py" into the editor. Run the file: 

```
C:\Users\noob_013\PycharmProjects\WBR\venv\Scripts\python.exe C:/Users/noob_013/PycharmProjects/WBR/main.py
Traceback (most recent call last):
  File "C:\Users\noob_013\PycharmProjects\WBR\main.py", line 205, in <module>
    app = App()
  File "C:\Users\noob_013\PycharmProjects\WBR\main.py", line 68, in __init__
    self.switch_1 = customtkinter.CTkSwitch(master=self.frame_left)
AttributeError: module 'customtkinter' has no attribute 'CTkSwitch'

Process finished with exit code 1
```

After deleting the lines containing 'CtkSwitch'.. I got : 

```
C:\Users\noob_013\PycharmProjects\WBR\venv\Scripts\python.exe C:/Users/noob_013/PycharmProjects/WBR/main.py
Traceback (most recent call last):
  File "C:\Users\noob_013\PycharmProjects\WBR\main.py", line 198, in <module>
    app = App()
  File "C:\Users\noob_013\PycharmProjects\WBR\main.py", line 106, in __init__
    self.radio_button_1 = customtkinter.CTkRadioButton(master=self.frame_right,
AttributeError: module 'customtkinter' has no attribute 'CTkRadioButton'

Process finished with exit code 1
```

Desktop:
OS: Windows 10
PyCharm 2022.1 (Community Edition)
Python 3.9.7

**Comment by NoobGamesDev** [comment]
Opened a brand new Python project and used the terminal inside PyCharm to install CustomTkinter.

```
pip3 install customtkinter
Collecting customtkinter
Downloading customtkinter-3.11-py3-none-any.whl
```

Now version 3.11 is installed, instead of 2.4. Complex_example.py is working like a charm. 
Closing issue. Issue solved.
