### ISSUE TITLE
Error while running my application : "pyi_rth_multiprocessing" #auto-py to exe

### ISSUE THREAD

**Issue by anshu-create** [TomSchimansky/CustomTkinter#850]
something like this shows every time: 

Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'

please somebody help me!
I had written the pyinstaller code given in the official document.

**Comment by anshu-create** [comment]
sorry, it was a **mistake**, I am literally a **beginner** so when pyinstaller build the app I was going into the **build folder** to open the .exe then from searching here and there I got to know that there is [**user\<user_name>\dist\<your_file>** ] then I clicked the file which then successfully executed :)

NOTE: YOU SHOULD FOLLOW THE OFFICIAL DOCUMENTATION TO AVOID ANY UNNECESSARY ERRORS
