### ISSUE TITLE
Change default icon for app failing in Linux for Customtkinter but working for tkinter.

### ISSUE THREAD

**Issue by Free-Radical** [TomSchimansky/CustomTkinter#879]
Hi the following code fails **(which works for regular Tkinter**), code changes the default icon displayed for running app
PLS ADVISE:

    logo = tkinter.PhotoImage(file='LOGO.png')
    root_window.call('wm', 'iconphoto', root_window._w, logo)

```
    root_window.call('wm', 'iconphoto', root_window._w, logo)
_tkinter.TclError: can't use "pyimage18" as iconphoto: not a photo image
Exception ignored in: <function Image.__del__ at 0x7f279d41f640>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/tkinter/__init__.py", line 4047, in __del__
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by Akascape** [comment]
@Free-Radical 
Try this:
```python
from PIL import ImageTk

logo = ImageTk.PhotoImage(file="LOGO.png") 
root_window.iconphoto(False, logo)
```

**Comment by Free-Radical** [comment]
Thanks @Akascape, tried,  didnt work, error:

`    root_window.iconphoto(False, logo)
  File "/opt/conda/lib/python3.10/tkinter/__init__.py", line 2156, in wm_iconphoto
    self.tk.call('wm', 'iconphoto', self._w, *args)
_tkinter.TclError: can't use "pyimage18" as iconphoto: not a photo image`

**Comment by Akascape** [comment]
@Free-Radical Try tkinter's photoimage
```python
logo = tkinter.PhotoImage(file="LOGO.png") 
root_window.iconphoto(False, logo)
```

**Comment by Free-Radical** [comment]
@Akascape didnt work with tkinter.PhotoImage either-

`    root_window.iconphoto(False, logo)
  File "/opt/conda/lib/python3.10/tkinter/__init__.py", line 2156, in wm_iconphoto
    self.tk.call('wm', 'iconphoto', self._w, *args)
_tkinter.TclError: can't use "pyimage18" as iconphoto: not a photo image
Exception ignored in: <function Image.__del__ at 0x7f7267273640>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/tkinter/__init__.py", line 4047, in __del__
TypeError: catching classes that do not inherit from BaseException is not allowed`

**Comment by Akascape** [comment]
@Free-Radical Try with a different png file.

**Comment by Free-Radical** [comment]
@Akascape , tried new png , same error

`    root_window.iconphoto(False, logo)
  File "/opt/conda/lib/python3.10/tkinter/__init__.py", line 2156, in wm_iconphoto
    self.tk.call('wm', 'iconphoto', self._w, *args)
_tkinter.TclError: can't use "pyimage18" as iconphoto: not a photo image
Exception ignored in: <function Image.__del__ at 0x7f93d23a7640>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/tkinter/__init__.py", line 4047, in __del__
TypeError: catching classes that do not inherit from BaseException is not allowed`

**Comment by Akascape** [comment]
@Free-Radical 
Maybe this work?

```python
from PIL import ImageTk, Image
logo = ImageTk.PhotoImage(Image.open("LOGO.png"))
```

Or

```python
from PIL import Image
logo = customtkinter.CTkImage(Image.open("LOGO.png"))
```

**Comment by D-Ayden** [comment]
I have a similar question, this is my code
```python
from base64 import b64decode

b64Icon = b"my icon base64"
icon = b64decode(b64Icon)

# import tkinter
# app = tkinter.Tk()

# # app.iconbitmap("./logo.ico")
# # print(ImageTk.PhotoImage(data=icon))
# print(app._w)
# print(app.tk)
# app.tk.call("wm", "iconphoto", app._w, ImageTk.PhotoImage(data=icon))
# app.mainloop()


import customtkinter
from PIL import ImageTk

app = customtkinter.CTk()
print(app.tk)
print(app._w)
app.tk.call("wm", "iconphoto", app._w, ImageTk.PhotoImage(data=icon))
app.mainloop()
```

it isn't working for customtkinter but working for tkinter.
Why?

**Comment by amiraligpu** [comment]
I also have same problem but with different error
![image](https://github.com/TomSchimansky/CustomTkinter/assets/108950264/c7f6b2f0-5ddb-442e-ab8c-655b1e22d031)
Details:

  Message=[Errno 2] No such file or directory: 'app_logo.ico'
  Source= PATH
  StackTrace:
  File PATH line 29, in open_gui
    logo = ImageTk.PhotoImage(file="app_logo.ico")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File PATH in <module> (Current frame)
    open_gui()
FileNotFoundError: [Errno 2] No such file or directory: 'app_logo.ico'

but it exists:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/108950264/bd2f3741-2aeb-4acb-8f2b-40f0f21dc9b2)
