### ISSUE TITLE
ValueError: ['text_font'] are not supported arguments

### ISSUE THREAD

**Issue by GermanYoshi** [TomSchimansky/CustomTkinter#962]
I Upgraded from 4.6.3 to the newest Version an get the following Error:
(I also tried Installing 5.0.0 to 5.0.3)

PS H:\06 Coding\VsCodeProjekts\FiLoS\v2.2.1> & C:/Users/werner/AppData/Local/Programs/Python/Python311/python.exe "h:/06 Coding/VsCodeProjekts/FiLoS/v2.2.1/filos.py"
Traceback (most recent call last):
  File "h:\06 Coding\VsCodeProjekts\FiLoS\v2.2.1\filos.py", line 281, in <module>
    app = App()
          ^^^^^
  File "h:\06 Coding\VsCodeProjekts\FiLoS\v2.2.1\filos.py", line 97, in __init__
    self.label_1 = customtkinter.CTkButton(master=self.frame_left,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\werner\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 52, in __init__
    super().__init__(master=master, bg_color=bg_color, width=width, height=height, **kwargs)
  File "C:\Users\werner\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 48, in __init__
    check_kwargs_empty(kwargs, raise_error=True)
  File "C:\Users\werner\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\utility\utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['text_font'] are not supported arguments. Look at the documentation for supported arguments.
PS H:\06 Coding\VsCodeProjekts\FiLoS\v2.2.1>

**Comment by Akascape** [comment]
@GermanYoshi Some parameters were changed after the new update. replace the `text_font` parameter with `font`. 
You can see the full change log here: https://github.com/TomSchimansky/CustomTkinter/blob/master/CHANGELOG.md#changed

**Comment by GermanYoshi** [comment]
@Akascape thanks

**Comment by Akascape** [comment]
@GermanYoshi Close this issue.

**Comment by Akascape** [comment]
@GermanYoshi Please close this issue!

**Comment by GermanYoshi** [comment]
cant...
