### ISSUE TITLE
Packing script to exe

### ISSUE THREAD

**Issue by soyTorch** [TomSchimansky/CustomTkinter#976]
Yo, I have this issue when I try to run the exe that has been generated by this command line:
pyinstaller --noconfirm --onefile --windowed --add-data "C:/Users/didac/AppData/Local/Programs/Python/Python310/Lib/site-packages/customtkinter;customtkinter/" --onedir "main.py"

![image](https://user-images.githubusercontent.com/96847130/210158887-11448d52-e66e-4b52-9f32-d2c1fef8c811.png)

What's going on?
This is the error message:

```
Traceback (most recent call last):
  File "customtkinter\windows\widgets\theme\__init__.py", line 5, in <module>
  File "customtkinter\windows\widgets\theme\theme_manager.py", line 18, in load_theme
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\didac\\AppData\\Local\\Temp\\_MEI244242\\customtkinter\\windows\\widgets\\theme\\../../../assets\\themes\\blue.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\windows\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\windows\ctk_tk.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\windows\widgets\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\windows\widgets\ctk_button.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "customtkinter\windows\widgets\theme\__init__.py", line 7, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\didac\\AppData\\Local\\Temp\\_MEI244242\\customtkinter\\windows\\widgets\\theme\\../../../assets\\themes\\blue.json'

The .json theme file for CustomTkinter could not be found.
If packaging with pyinstaller was used, have a look at the wiki:
https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging#windows-pyinstaller-auto-py-to-exe
```

Thanks!

**Comment by Akascape** [comment]
Add the folder customtkinter properly. Try to paste that folder inside the one dir directly

**Comment by Akascape** [comment]
Add the folder customtkinter properly. Try to paste that folder inside the one dir directly

Here is a detailed guide: https://github.com/TomSchimansky/CustomTkinter/discussions/939
